apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: wordpress
        image: bitnami/wordpress:6.4.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: wordpress-storage
          mountPath: /bitnami/wordpress
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: WORDPRESS_DATABASE_HOST
          value: "sql-bcp-itn.mysql.database.azure.com"
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mysql-user
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: mysql-password
        - name: ALLOW_EMPTY_PASSWORD
          value: "no"
        - name: WORDPRESS_DATABASE_NAME
          value: "db-bcp-itn"
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: pvc-nfs