apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
  namespace: wordpress
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - vers=3
  nfs:
    server: 10.100.0.148
    path: /${netappvolume}
