# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-secret-class
  namespace: wordpress
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: 604bd96f-2db2-451f-9be1-95f1eb92946e   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: kv-bcp-njff4zl344wqc-itn     # DYNAMIC
    cloudName: ""                         
    objects:  |
      array:
        - |
          objectName: mysql-database-user
          objectType: secret
          objectVersion: ""
        - |
          objectName: mysql-database-host
          objectType: secret              
          objectVersion: ""              
        - |
          objectName: mysql-database-password
          objectType: secret
          objectVersion: ""              
        - |
          objectName: mysql-database-name
          objectType: secret              
          objectVersion: ""
    tenantId: ea940877-ee38-4d12-9bc2-9d1f97d25dd7 # DYNAMIC
  secretObjects:                       
    - data:
      - key: mysql-database-user        
        objectName: mysql-database-user  
      - key: mysql-database-host
        objectName: mysql-database-host
      - key: mysql-database-password
        objectName: mysql-database-password
      - key: mysql-database-name
        objectName: mysql-database-name
      secretName: keyvault-secrets
      type: Opaque                       