# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-secret-class
  namespace: wordpress
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          
    userAssignedIdentityID: "${clientid}"
    keyvaultName: "${keyvaultname}"     
    cloudName: ""                         
    objects:  |
      array:
        - |
          objectName: mysql-database-user
          objectType: secret
          objectVersion: ""
        - |
          objectName: mysql-database-host
          objectType: secret              
          objectVersion: ""              
        - |
          objectName: mysql-database-password
          objectType: secret
          objectVersion: ""              
        - |
          objectName: mysql-database-name
          objectType: secret              
          objectVersion: ""
    tenantId: "${tenantid}" 
  secretObjects:                       
    - data:
      - key: mysql-database-user        
        objectName: mysql-database-user  
      - key: mysql-database-host
        objectName: mysql-database-host
      - key: mysql-database-password
        objectName: mysql-database-password
      - key: mysql-database-name
        objectName: mysql-database-name
      secretName: keyvault-secrets
      type: Opaque                       