apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: LoadBalancer           # Use LoadBalancer for external IP (if your cluster supports it)
  ports:
    - port: 80     
      targetPort: 8080            # External port
  selector:
    app: wordpress
