apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: wordpress
spec:
  containers:
  - image: busybox
    command:
    - "/bin/sh"
    - "-c"
    - "sleep 3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: disk01
      mountPath: /mnt/azure
  volumes:
  - name: disk01
    persistentVolumeClaim:
      claimName: pvc-nfs
