apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpluca
  namespace: wordpress
  labels:
    app: wpluca
    k8slens-edit-resource-version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wpluca
      tier: frontend
  template:
    metadata:
      labels:
        app: wpluca
        tier: frontend
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-nfs
      containers:
        - name: wordpress
          image: wordpress:6.2
          ports:
            - name: wordpress
              containerPort: 80
              protocol: TCP
          env:
            - name: TAR_OPTIONS
              value: '--no-same-owner'
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
          volumeMounts:
            - name: data
              mountPath: /var/www/html
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer