apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-nfs
      containers:
        - image: wordpress
          name: wordpress
          env:
          - name: WORDPRESS_DB_HOST
            value: "sql-bicepdeploy-itn.mysql.database.azure.com"
          - name: WORDPRESS_DB_PASSWORD
            value: Password123?
          - name: WORDPRESS_DB_USER
            value: azureuser
          - name: WORDPRESS_DB_NAME
            value: db-bicepdeploy-itn
          ports:
          - containerPort: 80
            name: wordpress
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /var/www/html
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
  strategy:
    type: Recreate
