# --------------------------
# Deployment (app1) - writes to subfolder "app1"
# --------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-pod1
  namespace: app1-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer-pod1
  template:
    metadata:
      labels:
        app: writer-pod1
    spec:
      initContainers:
        - name: init-create-app1-dir
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              # create the app1 subfolder and make it writable (best-effort)
              mkdir -p /mnt/azure/app1 && chmod 0777 /mnt/azure/app1 || true
          volumeMounts:
            - name: anf-volume
              mountPath: /mnt/azure
      containers:
        - name: writer
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                date '+%Y-%m-%d %H:%M:%S' >> /data/hello.log
                echo "Hello from pod1" >> /data/hello.log
                sleep 300
              done
          volumeMounts:
            - name: anf-volume
              mountPath: /data
              subPath: app1
      volumes:
        - name: anf-volume
          persistentVolumeClaim:
            claimName: anf-pvc-1
---
# --------------------------
# Deployment (app2) - writes to subfolder "app2"
# --------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-pod2
  namespace: app2-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer-pod2
  template:
    metadata:
      labels:
        app: writer-pod2
    spec:
      initContainers:
        - name: init-create-app2-dir
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /mnt/azure/app2 && chmod 0777 /mnt/azure/app2 || true
          volumeMounts:
            - name: anf-volume
              mountPath: /mnt/azure
      containers:
        - name: writer
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                date '+%Y-%m-%d %H:%M:%S' >> /data/hello.log
                echo "Hello from pod2" >> /data/hello.log
                sleep 300
              done
          volumeMounts:
            - name: anf-volume
              mountPath: /data
              subPath: app2
      volumes:
        - name: anf-volume
          persistentVolumeClaim:
            claimName: anf-pvc-2
