apiVersion: v1
kind: PersistentVolume
metadata:
  name: anf-pv-app2
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - vers=3
  nfs:
    server: 10.100.0.148
    path: /vol-routing-itn