apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anf-pvc-3
  namespace: shared-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi