apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anf-pvc-1
  namespace: app1-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi