apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anf-pvc-2
  namespace: app2-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
