apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-netapp-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - vers=3
  nfs:
    server: 0.0.0.0
    path: /volumename
