apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: wordpress-netapp-pv
  resources:
    requests:
      storage: 50Gi