apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile
  namespace: testfileshare
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-premium
  resources:
    requests:
      storage: 100Gi
